---
# nodeos
nodeos_container_image: "{{ nodeos_image }}"
nodeos_container_name: "eos-nodeos"
nodeos_container_network: "{{ docker_network_name }}"

nodeos_config_dir: "{{ eos_nodeos_config_location }}"
nodeos_data_dir: "{{ eos_nodeos_data_location }}"
nodeos_snapshot_url: "https://snapshots.greymass.network/eos/latest.tar.gz"
nodeos_snapshots_dir: "/tmp/eos_snapshots"

nodeos_chain_state_dbsize: "64000"
nodeos_validation_mode: "light"
nodeos_trace_history: "true"
nodeos_chain_state_history: "true"
nodeos_plugins:
  - "plugin = eosio::chain_plugin"
  - "plugin = eosio::net_plugin"
  - "plugin = eosio::state_history_plugin"
  - "plugin = eosio::chain_api_plugin"
  - "plugin = eosio::http_plugin"
nodeos_peer_addresses:
  - "p2p-peer-address = peer.main.alohaeos.com:9876"
  - "p2p-peer-address = p2p.eosflare.io:9876"
  - "p2p-peer-address = eos.seed.eosnation.io:9876"
  - "p2p-peer-address = peer1.eosphere.io:9876"
  - "p2p-peer-address = mainnet.eosamsterdam.net:9876"
  - "p2p-peer-address = p2p2.eoseoul.io:30333"
  - "p2p-peer-address = p2p.eosargentina.io:9876"

# lightapi dbwrite
lightapi_container_image: "{{ lightapi_image }}"
lightapi_container_network: "{{ docker_network_name }}"
lightapi_dbwrite_container_name: "eos-lightapi-dbwrite"
lightapi_dbwrite_port: "8080"
mariadb_host: "{{ mariadb_hostname }}"
# this value is hardcoded as is in lightapi
mariadb_db: "lightapi"
mariadb_user: "lightapi"
mariadb_password: "{{ lightapi_db_password }}"

# chronicle
chronicle_container_image: "{{ chronicle_image }}"
chronicle_container_name: "eos-chronicle"
chronicle_container_network: "{{ docker_network_name }}"
chronicle_config_dir: "{{ eos_chronicle_config_location }}"
chronicle_data_dir: "{{ eos_chronicle_data_location }}"
